NOTED THIS IS RUN USING JUPYTER NOTEBOOK. THE VISUAL STUDIO CODE IS FOR CODE READER. 
GET THE TOKEN FROM THE ANACONDA PROMPT

Tips : press 'Esc' + 'a' or 'b' to create code

In [2]:
import numpy as np

In [3]:
np.__version__

'2.4.3'

## Create & Read

#### 1D Array

In [10]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr1

array([1, 2, 3, 4, 5, 6])

In [11]:
type(arr1)

numpy.ndarray

In [12]:
arr1.shape # Printing the number of elements. This is like tuple

(6,)

In [13]:
arr1.dtype

dtype('int64')

In [14]:
arr1.ndim

1

In [15]:
arr1.size

6

#### 2D Array - is just an array in another array

In [17]:
arr2 = np.array([[1, 4, 5], [6, 7,4]]) # 2D Array is just
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [18]:
arr2.ndim

2

In [ ]:
arr2.shape # 2, 3 because it is 2 row, 3 column)

(2, 3)

In [20]:
arr2.dtype

dtype('int64')

#### 3D Array (Array inside an array inside an array) # Nested Array

In [21]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) # 3D Array
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [22]:
arr3.ndim

3

In [ ]:
arr3.shape # 2, 2, 3 because it is 2 layers. In each layers, there are 2 row, 3 column

(2, 2, 3)

In [24]:
arr3.size

12

### Create random array

In [26]:
randomArr = np.random.rand(3, 2, 3) # Give 3D Array with 3 layers, 2 row, 3 columns
randomArr

array([[[0.97679081, 0.38079396, 0.21794751],
        [0.61305793, 0.45212017, 0.01218578]],

       [[0.75722497, 0.43967875, 0.96500416],
        [0.84333331, 0.49384785, 0.0205244 ]],

       [[0.69860422, 0.0271789 , 0.98673571],
        [0.34234769, 0.14527796, 0.46197735]]])

In [28]:
randomArr.dtype

dtype('float64')

In [ ]:
zeroes = np.zeros((3, 2, 3)) # Give 3D Array with 3 layers, 2 row, 3 columns. But all values are zero
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [31]:
zeroes.ndim

3

In [32]:
full = np.full((3, 2, 3), 99) # Give 3D Array with 3 layers, 2 row, 3 columns. But all values are 99
full

array([[[99, 99, 99],
        [99, 99, 99]],

       [[99, 99, 99],
        [99, 99, 99]],

       [[99, 99, 99],
        [99, 99, 99]]])

In [34]:
ones = np.ones((3, 2, 3)) # Give 3D Array with 3 layers, 2 row, 3 columns. But all values are 1
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [35]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [41]:
# Get the first instance of the first layer
arr3[0][0][2]

np.int64(3)

In [48]:
# Slice this array
arr3[0:2, 0:1]

array([[[1, 2, 3]],

       [[7, 8, 9]]])

In [49]:
arr3[-1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [50]:
arr3[0][1][2]

np.int64(6)

#### Update & Delete

In [51]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [52]:
a1

array([[[0.60865105, 0.43032985],
        [0.2841608 , 0.23924968],
        [0.68922983, 0.44406606]],

       [[0.30968137, 0.8275626 ],
        [0.26336276, 0.88650318],
        [0.95969863, 0.55965404]]])

In [53]:
a2

array([[[0.11375551, 0.58145315],
        [0.30374381, 0.62127399],
        [0.4502582 , 0.86037178]],

       [[0.69514103, 0.61766361],
        [0.00426993, 0.03626035],
        [0.67155493, 0.07807575]]])

#### Basic Math Operation

In [54]:
np.add(a1, a2)

array([[[0.72240656, 1.011783  ],
        [0.58790461, 0.86052366],
        [1.13948803, 1.30443784]],

       [[1.0048224 , 1.44522621],
        [0.2676327 , 0.92276353],
        [1.63125355, 0.6377298 ]]])

In [55]:
np.subtract(a1, a2)

array([[[ 0.49489554, -0.1511233 ],
        [-0.019583  , -0.38202431],
        [ 0.23897164, -0.41630572]],

       [[-0.38545965,  0.20989899],
        [ 0.25909283,  0.85024283],
        [ 0.2881437 ,  0.48157829]]])

In [56]:
np.divide(a1, a2)

array([[[ 5.35051933,  0.74009376],
        [ 0.93552789,  0.38509528],
        [ 1.53074355,  0.51613276]],

       [[ 0.44549431,  1.33982736],
        [61.67840809, 24.44828029],
        [ 1.42906945,  7.16809025]]])

In [57]:
np.multiply(a1, a2)

array([[[0.06923741, 0.25021665],
        [0.08631208, 0.1486396 ],
        [0.31033138, 0.3820619 ]],

       [[0.21527223, 0.5111553 ],
        [0.00112454, 0.03214491],
        [0.64449034, 0.04369541]]])

#### Statistical Operation

In [ ]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

#### Update

In [59]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
arr3[0, 0, 2] = 500
arr3

array([[[  1,   2, 500],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])

In [63]:
arr3.sort()
arr3

array([[[  1,   2, 500],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])

In [75]:
# Reshape
arr3.shape

(2, 2, 3)

In [ ]:
arr3_reshape = arr3.reshape(1, 3, -1) # Reshape the array to 1 layer, 3 row, 4 column (if don't understand just type -1). Need to be careful about the number of elements. It should be the same as the original array
arr3_reshape

array([[[  1,   2, 500,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]]])

#### Appending and insercting

In [82]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [83]:
# Create a new array
new_array = np.ones((3, 2, 3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [85]:
appd = np.append(zeroes, new_array, axis=0) # axis 0 is row, axis 1 is column, axis 2 is layer
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### Insert

In [86]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [87]:
insterd_array = np.insert(zeroes, 2, new_array, axis=0) # Insert new_array into zeroes at index 2. axis 0 is row, axis 1 is column, axis 2 is layer
insterd_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

#### Delete

In [88]:
arr4 = np.random.rand(3, 2, 3)
arr4

array([[[0.70808988, 0.01847183, 0.97679054],
        [0.32155674, 0.34499342, 0.80444749]],

       [[0.8667495 , 0.30255475, 0.65848302],
        [0.96348678, 0.21693651, 0.67650138]],

       [[0.64119488, 0.50498056, 0.23636979],
        [0.33971918, 0.15414252, 0.467303  ]]])

In [90]:
# delete the array
arr5 = np.delete(arr4, 0, axis=1) # Delete first row of the array
arr5

array([[[0.32155674, 0.34499342, 0.80444749]],

       [[0.96348678, 0.21693651, 0.67650138]],

       [[0.33971918, 0.15414252, 0.467303  ]]])

In [91]:
np.save("new_array", arr5)

In [92]:
#### Load the Numpy array
np.load("new_array.npy")

array([[[0.32155674, 0.34499342, 0.80444749]],

       [[0.96348678, 0.21693651, 0.67650138]],

       [[0.33971918, 0.15414252, 0.467303  ]]])